---
- name: Verify Prometheus is reachable
  ansible.builtin.uri:
    url: http://127.0.0.1:9091/-/ready
    status_code: 200
  register: prom_ready
  retries: 10
  delay: 5
  until: prom_ready.status == 200

- name: Verify Grafana is reachable
  ansible.builtin.uri:
    url: http://127.0.0.1:3000/login
    status_code: 200
  register: grafana_ready
  retries: 10
  delay: 5
  until: grafana_ready.status == 200
