[sre_nodes]
# Replace with your VM public IP from Terraform output (instance_public_ip)
sre-vm ansible_host=127.0.0.1 ansible_user=ubuntu

[sre_nodes:vars]
project_path=/opt/sre-microservices
compose_file=docker-compose.yml
